/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlisinhvientinhnguyen.qlthanhvien;

//import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class themphantu extends javax.swing.JDialog {

    private DanhSachTV dstv;
    static String fileNameTV = "thanhvien.txt";
    ArrayList<ThanhVien> dsTV = new ArrayList<ThanhVien>();

    public themphantu(java.awt.Frame parent, boolean modal) {
        //luuuuu yyyy
        super(parent, modal);
        initComponents();
        fakeTV();
        this.setLocationRelativeTo(null);
        dstv = (DanhSachTV) parent;
        dstv.docFileTV(fileNameTV);
        dsTV = dstv.dsTV;
    }

    /**
     * Creates new form
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("nhap ma sv: ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("nhap ngay tham gia ");

        jTextField2.setText("yyyy-mm-dd");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("chuc vu : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thanh Vien", "Chủ CLB", "Phó CLB" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(78, 78, 78)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ArrayList<SinhVien> dsTVCC = new ArrayList<SinhVien>();

    public void fakeTV() {
        SinhVien a = new SinhVien("sinh vien 1", "2020604668", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien b = new SinhVien("sinh vien 2", "2020604669", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien c = new SinhVien("sinh vien 3", "2020604670", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien d = new SinhVien("sinh vien 4", "2020604667", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien a1 = new SinhVien("sinh vien 11", "2020604666", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien b1 = new SinhVien("sinh vien 21", "2020604665", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien c1 = new SinhVien("sinh vien 31", "2020604664", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        SinhVien d1 = new SinhVien("sinh vien 41", "2020604663", "nguyen xa", "CNTT", "KTPM03", "co Trinh");
        dsTVCC.add(a);
        dsTVCC.add(b);
        dsTVCC.add(c);
        dsTVCC.add(d);
        dsTVCC.add(a1);
        dsTVCC.add(b1);
        dsTVCC.add(c1);
        dsTVCC.add(d1);

//       dsTV.add(a);
//       dsTV.add(b);
//       dsTV.add(c);
//       dsTV.add(d);
        //  loadTable();
    }

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        boolean isMSV = false;
        boolean isMTV = true;
        for (SinhVien a : dsTVCC) {
            if (a.getmSV().equals(jTextField1.getText())) {
                isMSV = true;
            }
        }
        for (ThanhVien a : dsTV) {
            if (a.getmSV().equals(jTextField1.getText())) {
                isMTV = false;
            }
        }
        if (jTextField1.getText() == "" || jTextField2.getText() == "") {
            JOptionPane.showMessageDialog(rootPane, "khong duoc de trong o nao");
        } else {
            if (isMSV == false) {
                JOptionPane.showMessageDialog(rootPane, "khong co sinh vien nao trung khop");
            } else if (isMTV == false) {
                JOptionPane.showMessageDialog(rootPane, "sinh vien nay da la thanh vien");
            } else {
                boolean isOk = true;

                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                dateFormat.setLenient(false); // Chặn việc chuyển đổi chuỗi không hợp lệ
                try {
                    Date date = dateFormat.parse(jTextField2.getText());
                    System.out.println("Ngày tháng hợp lệ: " + date);
                } catch (Exception e) {
                    isOk = false;
                    JOptionPane.showMessageDialog(rootPane, "Ngay tháng phải đẻ dạng YYYY-MM-DD!");
                    System.out.println("Ngày tháng không hợp lệ: " + jTextField2.getText());
                }

                if (isOk == true) {
                    ThanhVien b = new ThanhVien();
                    for (SinhVien a : dsTVCC) {
//            System.out.println(a.getmSV() );
//            System.out.println(jTextField1.getText());

                        if (a.getmSV().equals(jTextField1.getText())) {
                            //b = a;
                            // b=new SinhVien(a.getTen(),a.getmSV(),a.getDiaChi(),a.getKhoa(),a.getLopUT(),a.getGiaoVien());
                            b.setTen(a.getTen());
                            b.setmSV(a.getmSV());
                            b.setDiaChi(a.getDiaChi());
                            b.setKhoa(a.getKhoa());
                            b.setLopUT(a.getLopUT());
                            b.setGiaoVien(a.getGiaoVien());
                            b.setChucVu((String) jComboBox1.getSelectedItem());
                            b.setNgayThamGia(jTextField2.getText());
                        }
                    }
                    System.out.println(b);
                    dstv.AddThanhVien(b);
                    JOptionPane.showMessageDialog(rootPane, "them thanh cong!!");
                }

            }
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themphantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themphantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themphantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themphantu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//               themphantu dialog = new themphantu((DanhSachTV) new javax.swing.JFrame(), true);
//
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
                //  themphantu dialog = new themphantu(frame, true);
                //luuuu yyyyyy
                DanhSachTV danhSachTV = new DanhSachTV();
                themphantu dialog = new themphantu(danhSachTV, true);

                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
